export default {
    ERR_CODE_USER_NOT_LOGGED_IN: -10007,
    // 服务程序错误
    ERR_CODE_SOMETHING_WENT_WRONG: -10002,
    // 场景不存在
    ERR_CODE_SCENE_DOES_NOT_EXIST: -20070,
    // 模型密码错误
    ERR_CODE_MODEL_PASSWORD_ERROR: -20082,
    // 模型需要密码
    ERR_CODE_MODEL_REQUIRES_PASSWORD: -20081,
    // 模型禁止访问
    ERR_CODE_MODEL_PROHIBITS_ACCESS: -20080,
};
